Update docs per webhook changes in the API
ArcadiaPower/platform-quickstart pull request #1
Opened 2021-06-07 18:03 UTC by clifff

Updating docs to reflect changes in https://github.com/ArcadiaPower/arcadia-power/pull/12048

2021-06-07 18:29 UTC, xelzi approved these changes

2021-06-07 18:29 UTC, xelzi commented on README.md
> +Open it and fill in your Arcadia API Client ID, API Client Secret. Leave `ARCADIA_WEBHOOK_SECRET` as is fow now - we'll come back to it.
```suggestion
Open it and fill in your Arcadia API Client ID, API Client Secret. Leave `ARCADIA_WEBHOOK_SECRET` as is for now - we'll come back to it.
```

2021-06-08 16:37 UTC, jakedouglas requested changes

2021-06-08 16:37 UTC, jakedouglas commented on README.md
> +Open it and fill in your Arcadia API Client ID, API Client Secret. Leave `ARCADIA_WEBHOOK_SECRET` as is for now - we'll come back to it.
```suggestion
Open it and fill in your Arcadia API Client ID, API Client Secret. Leave `ARCADIA_WEBHOOK_SIGNING_KEY` as is for now - we'll come back to it.
```

2021-06-08 16:37 UTC, jakedouglas commented on README.md
> +{"id":"YOUR_WEBHOOK_ID","url":"ARCADIA_TUNNELING_URL/webhook_listener","signing_key":"ARCADIA_WEBHOOK_SECRET","created_at":"2021-05-26T20:57:07.239-04:00","updated_at":"2021-05-26T20:57:07.239-04:00"
```suggestion
{"id":"YOUR_WEBHOOK_ID","url":"ARCADIA_TUNNELING_URL/webhook_listener","signing_key":"ARCADIA_WEBHOOK_SIGNING_KEY","created_at":"2021-05-26T20:57:07.239-04:00","updated_at":"2021-05-26T20:57:07.239-04:00"}
```

2021-06-08 20:07 UTC, johnnyman727 approved these changes

2021-06-08 20:27 UTC, merged